baseURL = "https://itsuki-jp.github.io/"
languageCode = "ja"
title = "n_itsuki's blog"
theme = "github_fork"
pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
  author = "n_itsuki"
  description = "社会人1年目"
  github = "itsuki-jp"
  twitter = "itsuki_jpnlonvn"
  url = "https://github.com/itsuki-jp"
  favicon = "/images/github-mark.png"
  avatar = "https://avatars.githubusercontent.com/u/63573439?v=4"
  headerIcon = "/images/github-mark-white.png"
  location = "Japan"
  userStatusEmoji = "😎"
  enableGitalk = false
  images=["/images/background_image.jpg"]
  [[params.links]]
    title = "Qiita"
    href = "https://qiita.com/n_itsuki"
    icon = "https://cdn.qiita.com/assets/public/push_notification/image-qiitan-572179a3bbde375850422ea48b2b6272.png"

enableGitInfo = true
[frontmatter]
  lastmod = ["lastmod", ":git", "date", "publishDate"]


[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = true


[taxonomies]
  category = 'categories'
  tag = 'tags'