baseURL = "https://itsuki-jp.github.io/"
languageCode = "ja"
title = "n_itsuki's blog"
theme = "github-style"
pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
  author = "n_itsuki"
  description = "社会人1年目"
  github = "itsuki-jp"
  twitter = "itsuki_jpnlonvn"
  url = "https://itsuki-jp.github.io/"
  favicon = "/images/github-mark.png"
  avatar = "/images/FEm5eHTVQAA1WwT2.jpg"
  headerIcon = "/images/github-mark-white.png"
  location = "Japan"
  userStatusEmoji = "😎"
  enableGitalk = false

  [params.gitalk]
    clientID = "Your client ID" # Your client ID
    clientSecret = "Your client secret" # Your client secret
    repo = "LuvSia" # 您的博客的github地址Repository name，例如：xxxx.github.io
    owner = "ventusoon" # 您的GitHub ID
    admin = "ventusoon" # 您的GitHub ID
    id = "location.pathname" # 文章页面的链接地址就是ID
    labels = "gitalk" # Github issue labels. If you used to use Gitment, you can change it
    perPage = 15 # Pagination size, with maximum 100.
    pagerDirection = "last" # Comment sorting direction, available values are 'last' and 'first'.
    createIssueManually = true # 设置为true，如果是管理员登录，会自动创建issue，如果是false，需要管理员手动添加第一个评论(issue)
    distractionFreeMode = false # Enable hot key (cmd|ctrl + enter) submit comment.
    proxy = "https://cors-anywhere.azm.workers.dev/https://github.com/login/oauth/access_token" # 可以自行添加反向代理
  [[params.links]]
    title = "Qiita"
    href = "https://qiita.com/n_itsuki"
    icon = "https://cdn.qiita.com/assets/public/push_notification/image-qiitan-572179a3bbde375850422ea48b2b6272.png"

[frontmatter]
  lastmod = ["lastmod", ":fileModTime", ":default"]

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = true